# docker compose for an ILP Kit
version: "2.0"
networks:
  kit:
services:

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    volumes:
      - "/data/postgres-data:/var/lib/postgresql/data"
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "ilp-kit-db"
      # TODO: should these be randomized?
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "${ILP_SECRET}"
    networks:
      kit:
        aliases:
          - "postgres"

  ilp-kit:
    depends_on:
      - postgres
    container_name: "ilp-kit"
    image: "colinwitkamp/ilp-kit:latest"
# enable this for development, with a local ilp-kit folder
#    build: "ilp-kit"
    volumes:
      - "/data/uploads:/usr/src/app/uploads"
      - "./env.list:/usr/src/app/env.list"
    networks:
      kit:
        aliases:
          - "ilp-kit"
    ports:
      - "3100:3100"
      - "3101:3101"
      - "3010:3010"

    environment:
      DB_URI: "postgres://admin:${ILP_SECRET}@postgres/ilp-kit-db"
      API_HOSTNAME: "${ILP_DOMAIN}"
      API_PORT: "3100"
      API_PRIVATE_HOSTNAME: "localhost"
      API_PUBLIC_HTTPS: "true"
      API_PUBLIC_PATH: "/api"
      API_PUBLIC_PORT: "443"
      API_SECRET: "${ILP_SECRET}"
      API_MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
      API_MAILGUN_DOMAIN: "${MAILGUN_DOMAIN}"
      CLIENT_HOST: "${ILP_DOMAIN}"
      CLIENT_PORT: "3010"
      CLIENT_PUBLIC_PORT: "443"
      CLIENT_TITLE: "${ILP_DOMAIN}"
      LEDGER_ADMIN_NAME: "admin"
      LEDGER_ADMIN_PASS: "${ILP_SECRET}"
      LEDGER_CURRENCY_CODE: "${ILP_CURRENCY}"
      LEDGER_ILP_PREFIX: "g.dev.${ILP_DOMAIN}."
      LEDGER_RECOMMENDED_CONNECTORS: "connector"
      CONNECTOR_ENABLE: "true"
      CONNECTOR_AUTOLOAD_PEERS: "true"
      CONNECTOR_MAX_HOLD_TIME: "100"
      CONNECTOR_LEDGERS: '{"g.dev.${ILP_DOMAIN}.":{"currency":"${ILP_CURRENCY}","plugin":"ilp-plugin-bells","options":{"account":"https://${ILP_DOMAIN}/ledger/accounts/connector","username":"connector","password":"${ILP_SECRET}"}}}'
      API_REGISTRATION: "true"
      LEDGER_AMOUNT_SCALE: "9"
      LEDGER_AMOUNT_PRECISION: "19"
      ILP_KIT_CLI_VERSION: "11.0.1"
      DEBUG: "connector*,ilp*"
      
